version: '3'

services:
  gitea:
    container_name: gitea
    image: gitea/gitea
    ports:
      - "3000:3000"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    volumes:
      - ./docker-compose/gitea_data:/data
    restart: always
    hostname: gitea.test

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
    volumes:
      - ./docker-compose/postgres_data:/var/lib/postgresql/data
    restart: always

  drone:
    container_name: drone
    image: drone/drone
    ports:
      - "80:80"
    environment:
      - DRONE_GITEA_SERVER=http://gitea.test:3000
      - DRONE_GITEA_CLIENT_ID=10ee209e-014c-4c27-a34c-97102261b5ba
      - DRONE_GITEA_CLIENT_SECRET=gto_uumuwiks4r5542lgsaftuz2gwsriwewumnr4kjwxubou35dkn4eq
    volumes:
      - ./docker-compose/drone_data:/var/lib/drone
    restart: always
    hostname: drone.test

volumes:
  gitea_data:
  postgres_data:
  drone_data: